export const metadata = {
  title: 'Terms of Service - CKR Decision Platform',
  description: 'Terms of Service for the CKR Decision Platform by Chakaralaya Analytics Private Limited.',
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl text-primary-dark mb-2">Terms of Service</h1>
      <p className="text-sm text-slate-400 mb-10">Last updated: 28 June 2026</p>

      <div className="space-y-8 text-sm text-slate-600 leading-relaxed">
        <Section title="1. Acceptance of Terms">
          By accessing or using the CKR Decision Platform (&quot;Platform&quot;) at mcdm.chakaralaya.in, operated by Chakaralaya Analytics Private Limited (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.
        </Section>

        <Section title="2. Description of Service">
          The Platform provides free multi-criteria decision making (MCDM) tools that allow users to evaluate alternatives across multiple criteria using 50+ decision science methods. The Platform generates analysis reports available for download in PDF and Word formats.
        </Section>

        <Section title="3. Account and Registration">
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>Use of the analysis tools does not require registration.</li>
            <li>Downloading reports (PDF/Word) requires signing in with a Google account and providing basic profile information.</li>
            <li>You are responsible for maintaining the confidentiality of your account and for all activities under your account.</li>
            <li>You must provide accurate and complete information when creating your profile.</li>
          </ul>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>Use the Platform for any unlawful purpose or in violation of any applicable laws.</li>
            <li>Attempt to gain unauthorized access to the Platform or its systems.</li>
            <li>Use automated scripts, bots, or scrapers to access the Platform without prior written consent.</li>
            <li>Redistribute, resell, or sublicense the Platform or its outputs as a competing service.</li>
            <li>Upload malicious data or attempt to compromise the integrity of the analysis engine.</li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          The Platform, including its design, analysis methods, code, and documentation, is the intellectual property of Chakaralaya Analytics Private Limited. Reports generated by the Platform may be used freely by the user for their own business or research purposes.
        </Section>

        <Section title="6. Data You Provide">
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>Decision data (criteria, alternatives, scores) you enter into the tools is processed in your browser and is not stored on our servers.</li>
            <li>Profile information (name, email, company/university details) provided during sign-in is stored securely and used as described in our Privacy Policy.</li>
          </ul>
        </Section>

        <Section title="7. Disclaimer of Warranties">
          The Platform is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. We do not warrant that the Platform will be uninterrupted, error-free, or free of harmful components. The analysis results are mathematical computations intended to support — not replace — human judgment and decision-making.
        </Section>

        <Section title="8. Limitation of Liability">
          To the maximum extent permitted by law, Chakaralaya Analytics Private Limited shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, arising out of or related to your use of the Platform.
        </Section>

        <Section title="9. Modifications">
          We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of the Platform after changes constitutes acceptance of the revised Terms.
        </Section>

        <Section title="10. Governing Law">
          These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.
        </Section>

        <Section title="11. Contact">
          For questions about these Terms, contact us at{' '}
          <a href="mailto:ckranalytics@gmail.com" className="text-accent hover:text-accent-hover transition-colors">
            ckranalytics@gmail.com
          </a>.
        </Section>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base text-primary-dark mb-3">{title}</h2>
      <div>{children}</div>
    </section>
  );
}
