export interface ToolConfig {
  slug: string;
  title: string;
  shortTitle: string;
  tagline: string; // 6 words max, action-oriented
  description: string;
  heroHeadline: string;
  heroSubtext: string;
  features: { bold: string; rest: string }[];
  category: 'procurement' | 'strategy';
  criteriaLabel: string;
  alternativesLabel: string;
  alternativeSingular: string;
  presetCriteria: { name: string; type: 'benefit' | 'cost' }[];
  icon: string;
  color: string;
}

export const TOOL_CONFIGS: Record<string, ToolConfig> = {
  'supplier-evaluation': {
    slug: 'supplier-evaluation',
    title: 'Supplier Evaluation',
    shortTitle: 'Supplier Evaluation',
    tagline: 'Rank suppliers across key criteria',
    description: 'Compare suppliers on price, quality, delivery, and reliability. Get a defensible ranking backed by 50+ methods.',
    heroHeadline: 'Evaluate suppliers with mathematical precision',
    heroSubtext: 'Run your supplier data through 50+ decision science methods. Get a defensible, auditable ranking in a downloadable PDF.',
    features: [
      { bold: 'Custom criteria', rest: 'price, quality, delivery, or anything you define' },
      { bold: '50+ methods', rest: 'TOPSIS, VIKOR, PROMETHEE and more run automatically' },
      { bold: 'PDF report', rest: 'full methodology breakdown, ready to share' },
    ],
    category: 'procurement',
    criteriaLabel: 'Evaluation Criteria',
    alternativesLabel: 'Suppliers',
    alternativeSingular: 'Supplier',
    presetCriteria: [
      { name: 'Price', type: 'cost' },
      { name: 'Quality', type: 'benefit' },
      { name: 'Delivery Time', type: 'cost' },
      { name: 'Reliability', type: 'benefit' },
    ],
    icon: 'truck',
    color: '#2563eb',
  },
  'vendor-selection': {
    slug: 'vendor-selection',
    title: 'Vendor Selection',
    shortTitle: 'Vendor Selection',
    tagline: 'Pick the right vendor, objectively',
    description: 'Compare vendors on cost, capability, experience, and support. Remove bias from vendor decisions.',
    heroHeadline: 'Select the right vendor, backed by data',
    heroSubtext: 'Remove bias from high-stakes vendor decisions. 50+ scientific methods cross-validate your ranking.',
    features: [
      { bold: 'Weighted scoring', rest: 'across cost, capability, experience and more' },
      { bold: 'Consensus analysis', rest: 'see how strongly methods agree on the winner' },
      { bold: 'Board-ready PDF', rest: 'executive summary with full audit trail' },
    ],
    category: 'procurement',
    criteriaLabel: 'Selection Criteria',
    alternativesLabel: 'Vendors',
    alternativeSingular: 'Vendor',
    presetCriteria: [
      { name: 'Cost', type: 'cost' },
      { name: 'Capability', type: 'benefit' },
      { name: 'Experience', type: 'benefit' },
      { name: 'Support', type: 'benefit' },
    ],
    icon: 'handshake',
    color: '#7c3aed',
  },
  'rfp-scoring': {
    slug: 'rfp-scoring',
    title: 'RFP Scoring',
    shortTitle: 'RFP Scoring',
    tagline: 'Score proposals beyond spreadsheets',
    description: 'Evaluate RFP responses on technical, financial, timeline, and risk factors with scientific rigor.',
    heroHeadline: 'Score RFP responses with scientific rigor',
    heroSubtext: 'Go beyond spreadsheet scoring. 50+ methods produce transparent, defensible proposal evaluations.',
    features: [
      { bold: 'Multi-factor scoring', rest: 'technical, financial, timeline and risk together' },
      { bold: 'Cross-validation', rest: 'eliminates single-method bias from rankings' },
      { bold: 'Transparent PDF', rest: 'Borda count, rank frequency, full methodology' },
    ],
    category: 'procurement',
    criteriaLabel: 'Scoring Criteria',
    alternativesLabel: 'Proposals',
    alternativeSingular: 'Proposal',
    presetCriteria: [
      { name: 'Technical Fit', type: 'benefit' },
      { name: 'Financial Offer', type: 'cost' },
      { name: 'Timeline', type: 'cost' },
      { name: 'Risk', type: 'cost' },
    ],
    icon: 'file-text',
    color: '#059669',
  },
  'tender-evaluation': {
    slug: 'tender-evaluation',
    title: 'Tender Evaluation',
    shortTitle: 'Tender Evaluation',
    tagline: 'Evaluate tenders transparently',
    description: 'Rank tenders on price, compliance, capability, and track record. Audit-ready results.',
    heroHeadline: 'Evaluate tenders with full transparency',
    heroSubtext: 'Rank tenders across weighted criteria with 50+ methods. Auditable, repeatable results.',
    features: [
      { bold: 'Compliance-first', rest: 'evaluate price, compliance, capability together' },
      { bold: 'Multiple weightings', rest: 'objective methods ensure robust conclusions' },
      { bold: 'Audit-ready', rest: 'PDF with methodology appendix for procurement review' },
    ],
    category: 'procurement',
    criteriaLabel: 'Evaluation Criteria',
    alternativesLabel: 'Tenders',
    alternativeSingular: 'Tender',
    presetCriteria: [
      { name: 'Price', type: 'cost' },
      { name: 'Compliance', type: 'benefit' },
      { name: 'Capability', type: 'benefit' },
      { name: 'Track Record', type: 'benefit' },
    ],
    icon: 'clipboard-check',
    color: '#dc2626',
  },
  'vendor-performance': {
    slug: 'vendor-performance',
    title: 'Vendor Performance',
    shortTitle: 'Vendor Performance',
    tagline: 'Benchmark vendors on KPIs',
    description: 'Compare vendor performance on delivery, defects, cost, and responsiveness.',
    heroHeadline: 'Benchmark vendor performance objectively',
    heroSubtext: 'Compare vendor KPIs using decision science. Identify top and bottom performers.',
    features: [
      { bold: 'KPI-based', rest: 'on-time delivery, defect rates, cost efficiency' },
      { bold: 'Objective weights', rest: 'CRITIC, ENTROPY and 8 more methods' },
      { bold: 'Shareable scorecard', rest: 'PDF for vendor review meetings' },
    ],
    category: 'procurement',
    criteriaLabel: 'KPIs',
    alternativesLabel: 'Vendors',
    alternativeSingular: 'Vendor',
    presetCriteria: [
      { name: 'On-time Delivery', type: 'benefit' },
      { name: 'Defect Rate', type: 'cost' },
      { name: 'Cost Efficiency', type: 'benefit' },
      { name: 'Responsiveness', type: 'benefit' },
    ],
    icon: 'bar-chart',
    color: '#ea580c',
  },
  'capex-approval': {
    slug: 'capex-approval',
    title: 'CAPEX Approval',
    shortTitle: 'CAPEX Approval',
    tagline: 'Prioritize capital expenditure projects',
    description: 'Rank CAPEX proposals on ROI, risk, strategic fit, and payback period.',
    heroHeadline: 'Prioritize capital projects with confidence',
    heroSubtext: 'Rank CAPEX proposals across ROI, risk, strategic fit, and payback with 50+ methods.',
    features: [
      { bold: 'Multi-factor', rest: 'ROI, risk, strategic fit, payback simultaneously' },
      { bold: 'Sensitivity analysis', rest: 'see how weight changes affect rankings' },
      { bold: 'Committee-ready', rest: 'PDF with executive summary and methodology' },
    ],
    category: 'strategy',
    criteriaLabel: 'Decision Factors',
    alternativesLabel: 'Projects',
    alternativeSingular: 'Project',
    presetCriteria: [
      { name: 'ROI', type: 'benefit' },
      { name: 'Risk', type: 'cost' },
      { name: 'Strategic Fit', type: 'benefit' },
      { name: 'Payback Period', type: 'cost' },
    ],
    icon: 'building',
    color: '#0891b2',
  },
  'project-prioritization': {
    slug: 'project-prioritization',
    title: 'Project Prioritization',
    shortTitle: 'Project Prioritization',
    tagline: 'Rank projects by real impact',
    description: 'Score projects on impact, feasibility, urgency, and cost. Cut through the noise.',
    heroHeadline: 'Prioritize the projects that matter most',
    heroSubtext: 'When everything is urgent, nothing is. Rank projects by impact, feasibility, and cost.',
    features: [
      { bold: 'Impact-driven', rest: 'score impact, feasibility, urgency and cost' },
      { bold: '25+ algorithms', rest: 'aggregated rankings for robust conclusions' },
      { bold: 'Consensus report', rest: 'PDF with rank distribution and agreement level' },
    ],
    category: 'strategy',
    criteriaLabel: 'Priority Criteria',
    alternativesLabel: 'Projects',
    alternativeSingular: 'Project',
    presetCriteria: [
      { name: 'Impact', type: 'benefit' },
      { name: 'Feasibility', type: 'benefit' },
      { name: 'Urgency', type: 'benefit' },
      { name: 'Cost', type: 'cost' },
    ],
    icon: 'layers',
    color: '#4f46e5',
  },
  'investment-decision': {
    slug: 'investment-decision',
    title: 'Investment Decision',
    shortTitle: 'Investment Decision',
    tagline: 'Compare opportunities analytically',
    description: 'Evaluate investments on return, risk, liquidity, and time horizon.',
    heroHeadline: 'Make investment decisions with analytical rigor',
    heroSubtext: 'Compare opportunities across return, risk, liquidity, and time horizon with 50+ methods.',
    features: [
      { bold: 'Full-picture', rest: 'return, risk, liquidity, time horizon together' },
      { bold: 'Stability check', rest: 'cross-method validation shows ranking confidence' },
      { bold: 'Committee PDF', rest: 'comprehensive report for investment review' },
    ],
    category: 'strategy',
    criteriaLabel: 'Investment Criteria',
    alternativesLabel: 'Opportunities',
    alternativeSingular: 'Opportunity',
    presetCriteria: [
      { name: 'Expected Return', type: 'benefit' },
      { name: 'Risk Level', type: 'cost' },
      { name: 'Liquidity', type: 'benefit' },
      { name: 'Time Horizon', type: 'cost' },
    ],
    icon: 'trending-up',
    color: '#16a34a',
  },
  'contract-evaluation': {
    slug: 'contract-evaluation',
    title: 'Contract Evaluation',
    shortTitle: 'Contract Evaluation',
    tagline: 'Pick the strongest contract terms',
    description: 'Compare contracts on pricing, SLAs, liability, and flexibility. Data-driven selection across all terms.',
    heroHeadline: 'Evaluate contracts beyond the price tag',
    heroSubtext: 'Rank contracts across pricing, SLAs, liability clauses, and flexibility using 50+ decision methods.',
    features: [
      { bold: 'Full-term analysis', rest: 'pricing, SLAs, liability, renewal clauses together' },
      { bold: 'Objective weighting', rest: 'data-derived importance removes negotiation bias' },
      { bold: 'Audit trail PDF', rest: 'methodology appendix for legal and procurement review' },
    ],
    category: 'procurement',
    criteriaLabel: 'Contract Criteria',
    alternativesLabel: 'Contracts',
    alternativeSingular: 'Contract',
    presetCriteria: [
      { name: 'Pricing', type: 'cost' },
      { name: 'SLA Terms', type: 'benefit' },
      { name: 'Liability', type: 'cost' },
      { name: 'Flexibility', type: 'benefit' },
    ],
    icon: 'document',
    color: '#b45309',
  },
  'technology-selection': {
    slug: 'technology-selection',
    title: 'Technology Selection',
    shortTitle: 'Technology Selection',
    tagline: 'Choose the right tech stack',
    description: 'Compare platforms, tools, or solutions on cost, scalability, integration, and support.',
    heroHeadline: 'Select technology with analytical confidence',
    heroSubtext: 'Compare platforms and tools across cost, scalability, integration, and vendor support with 50+ methods.',
    features: [
      { bold: 'Platform comparison', rest: 'cost, scalability, integration, support weighted fairly' },
      { bold: 'Cross-validated', rest: '50+ methods ensure the ranking holds from every angle' },
      { bold: 'Stakeholder PDF', rest: 'shareable report for steering committee review' },
    ],
    category: 'strategy',
    criteriaLabel: 'Selection Criteria',
    alternativesLabel: 'Technologies',
    alternativeSingular: 'Technology',
    presetCriteria: [
      { name: 'Total Cost', type: 'cost' },
      { name: 'Scalability', type: 'benefit' },
      { name: 'Integration', type: 'benefit' },
      { name: 'Vendor Support', type: 'benefit' },
    ],
    icon: 'cpu',
    color: '#9333ea',
  },
  'risk-assessment': {
    slug: 'risk-assessment',
    title: 'Risk Assessment',
    shortTitle: 'Risk Assessment',
    tagline: 'Rank risks by real severity',
    description: 'Prioritize risks by impact, likelihood, detectability, and mitigation cost. Focus resources where they matter.',
    heroHeadline: 'Prioritize risks with mathematical precision',
    heroSubtext: 'Rank risks across impact, probability, detectability, and mitigation cost using 50+ decision methods.',
    features: [
      { bold: 'Multi-dimensional', rest: 'impact, likelihood, detectability, cost together' },
      { bold: 'Beyond risk matrices', rest: '50+ methods replace crude high/medium/low grids' },
      { bold: 'Risk register PDF', rest: 'ranked risk report for compliance and governance' },
    ],
    category: 'strategy',
    criteriaLabel: 'Risk Factors',
    alternativesLabel: 'Risks',
    alternativeSingular: 'Risk',
    presetCriteria: [
      { name: 'Impact', type: 'cost' },
      { name: 'Likelihood', type: 'cost' },
      { name: 'Detectability', type: 'benefit' },
      { name: 'Mitigation Cost', type: 'cost' },
    ],
    icon: 'shield',
    color: '#e11d48',
  },
};

export const TOOL_SLUGS = Object.keys(TOOL_CONFIGS);
